# Site settings
title: Gonster
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://gonster.github.io" # the base hostname & protocol for your site
github_username:  Gonster
paginate: 15
paginate_path: "/page:num/"

# Build settings
markdown: kramdown
highlighter: Rouge
